[project]
name = "ai-engg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-contrib-python>=4.11.0.86",
    "opencv-python>=4.11.0.86",
    "transformers>=4.52.4",
]
